# Generated by Django 4.0.6 on 2022-07-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_tradetype_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradetype',
            old_name='status',
            new_name='trade_type',
        ),
    ]
