# Generated by Django 4.0.6 on 2022-08-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_delete_offer_delete_seller_delete_tradetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='converter.currency', verbose_name='Payment Method Currency'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Payment Method Create/Update Date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Payment Method Name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Payment Method Identifier'),
        ),
    ]
