# Generated by Django 4.0.6 on 2022-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_currency_code_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetype',
            name='status',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell')], default='BUY', max_length=3),
        ),
    ]
