# Generated by Django 4.0.6 on 2022-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_alter_paymentmethod_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
