# Generated by Django 4.0.6 on 2022-08-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_paymentmethod_date_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='TradeType',
        ),
    ]
