# Generated by Django 4.0.6 on 2022-07-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_rename_paymentmethods_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
