# Generated by Django 4.0.6 on 2022-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_alter_paymentmethod_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
